### ISSUE TITLE
Using GlassPanePopup.install(this); in multi JFrames constructors

### ISSUE THREAD

**Issue by mad960** [DJ-Raven/swing-glasspane-popup#4]
While I am using MessageAlerts.getInstance().showMessage() as confirm dialog in many buttons and operation and many JFrames, I faced recently a problem when working in more than JFrame at the same time.
The problem is the confirm dialog does not appear in the JFrame I am using because it previously appeared on another JFrame, I tried to use GlassPanePopup.install(this); in some window events like focus gained and activated but also did not work and gives me run errors in miglayout, the initialization just works in constructors for some reason.
I embed directly the project's code and tried to solve it, while I couldn't, I suggest the next update to be non-static, like each JFrame will have its own GlassPanePopup and use install in constructor, and also we could pass the local GlassPanePopup to MessageAlerts.getInstance().showMessage(), I tried to edit all the project code to use non-static variables, but I don't have much time, so I stopped and writing this issue, hoping to solve it as a new branch.

**Comment by DJ-Raven** [comment]
This glassPane popup do not support muti jframe install. but you can try modal dialog project [here](https://github.com/DJ-Raven/swing-modal-dialog)

this modal dialog project no need to install the frame

``` java
ModalDialog.showModal(this,
        new SimpleModalBorder(new JLabel("Sample message text"),
                "Message",
                SimpleModalBorder.YES_NO_OPTION,
                (controller, action) -> {
                    if (action == SimpleModalBorder.YES_OPTION) {
                        // yes option
                    }
                }));
```

**Comment by mad960** [comment]
Thanks for fast responding, I am trying, it is animated like MessageAlerts.getInstance().showMessage()? If it is, can you please provide me an example of usage.

**Comment by DJ-Raven** [comment]
@mad960 here you can check my commit [here](https://github.com/DJ-Raven/swing-modal-dialog/commit/59815380c9edac64964113e5596cd9335112c7d2) and [demo test class](https://github.com/DJ-Raven/swing-modal-dialog/blob/main/demo/src/test/java/test/TestAlerts.java)

![2024-07-08_131304](https://github.com/DJ-Raven/swing-glasspane-popup/assets/58245926/430632f0-e18b-4679-b5ff-55dcbc78c8b4)
